# Generated by Django 4.1.1 on 2022-09-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Материал')),
                ('passport', models.FileField(upload_to='', verbose_name='Файл паспорта материала')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование проекта')),
                ('template', models.FileField(upload_to='', verbose_name='Файл-шаблон')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип акта')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер акта')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер акта в проекте')),
                ('act_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acts.type', verbose_name='Тип акта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='acts.project', verbose_name='Проект')),
            ],
        ),
    ]
