# Generated by Django 4.1.1 on 2022-09-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_project_result_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acts.type', verbose_name='Тип акта'),
        ),
    ]
