# Generated by Django 4.1.1 on 2022-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_alter_act_act_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='materials',
            field=models.ManyToManyField(related_name='materials', to='acts.material', verbose_name='Материалы'),
        ),
    ]
