# Generated by Django 4.1.1 on 2022-09-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0005_alter_material_passport_alter_project_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='works',
            field=models.CharField(default='Съедено 1999 жуков', max_length=500, verbose_name='Проведенные работы'),
            preserve_default=False,
        ),
    ]
