# Generated by Django 4.1.1 on 2022-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0006_act_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип акта'),
        ),
    ]
