# Generated by Django 4.1.1 on 2022-09-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0007_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='acts.project', verbose_name='Проект'),
        ),
    ]
