# Generated by Django 4.1.1 on 2022-09-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0008_alter_act_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/passports/', verbose_name='Файл паспорта материала')),
            ],
        ),
        migrations.AlterField(
            model_name='act',
            name='act_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acts.type', verbose_name='Тип акта'),
        ),
        migrations.AlterField(
            model_name='material',
            name='passport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acts.passport', verbose_name='Паспорт материала'),
        ),
    ]
