# Generated by Django 4.1.1 on 2022-09-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0009_passport_alter_act_act_type_alter_material_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='passport',
            field=models.FileField(default=None, upload_to='files/passports/', verbose_name='Файл паспорта материала'),
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
