# Generated by Django 4.1.1 on 2022-09-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0010_alter_material_passport_delete_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, related_name='materials', to='acts.material', verbose_name='Материалы'),
        ),
    ]
