# Generated by Django 4.1.1 on 2022-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0011_alter_act_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='date_end',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата конца работ'),
        ),
        migrations.AddField(
            model_name='act',
            name='date_start',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата начала работ'),
        ),
        migrations.AlterField(
            model_name='act',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='materials', to='acts.material', verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Материал'),
        ),
    ]
